/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author ar466
 */
public class Juego extends javax.swing.JFrame {
    DatosUsuario datos;
    Login login;
    Menu menu;
    Usuarios usuarios;
    Date fecha= new Date();
   
   
    /**
     * Creates new form Juego
     */
    public Juego(Login login, DatosUsuario datos) {
        initComponents();
        this.datos = datos;
        this.login = login;
        
        //definir tamano y centrar el tablero
        this.setSize(1300, 820);
        this.setLocationRelativeTo(null);
        setVisible(true);
        
        Tablero.setLayout(new GridLayout(1,1));
        Tablero.setMinimumSize(new Dimension(600, 300));
        Tablero.add(new TableroStratego(datos, login, txtAreaEliminados, lblTurnos, this));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tablero = new javax.swing.JPanel();
        Eliminados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEliminados = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lblTurnos = new javax.swing.JLabel();
        btnRendirse = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Marvel Stratego - En Partida");
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Stratego logo izquierda.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TableroLayout = new javax.swing.GroupLayout(Tablero);
        Tablero.setLayout(TableroLayout);
        TableroLayout.setHorizontalGroup(
            TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
        TableroLayout.setVerticalGroup(
            TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Eliminados.setLayout(null);

        txtAreaEliminados.setBackground(new java.awt.Color(189, 197, 5));
        txtAreaEliminados.setColumns(20);
        txtAreaEliminados.setRows(5);
        jScrollPane1.setViewportView(txtAreaEliminados);

        Eliminados.add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 290, 590);

        jLabel4.setBackground(new java.awt.Color(19, 153, 242));
        jLabel4.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel4.setText("PERSONAJES ELIMINADOS");
        Eliminados.add(jLabel4);
        jLabel4.setBounds(50, 10, 240, 30);

        lblTurnos.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lblTurnos.setForeground(new java.awt.Color(255, 255, 255));
        lblTurnos.setText("Turno de: ");
        lblTurnos.setToolTipText("");
        Eliminados.add(lblTurnos);
        lblTurnos.setBounds(40, 740, 160, 30);

        btnRendirse.setBackground(new java.awt.Color(58, 148, 181));
        btnRendirse.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnRendirse.setForeground(new java.awt.Color(255, 255, 255));
        btnRendirse.setText("Rendirse");
        btnRendirse.setToolTipText("");
        btnRendirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendirseActionPerformed(evt);
            }
        });
        Eliminados.add(btnRendirse);
        btnRendirse.setBounds(70, 690, 190, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo marvel.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        Eliminados.add(jLabel2);
        jLabel2.setBounds(0, 0, 330, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Eliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Eliminados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRendirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRendirseActionPerformed
        // TODO add your handling code here:
        int confirmacion = JOptionPane.showConfirmDialog(null,"Desea rendirse? Apretar Yes para rendirse, Apretar No para seguir jugando", "Cambio de Turno", JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION){
            String perdedor = lblTurnos.getText().substring(10);
            String ganador;
             
            if (perdedor.equals(datos.UsuarioLogeado)){ 
                 ganador = datos.SegundoUsuario;

              if (TableroStratego.esHeroe) {
                JOptionPane.showMessageDialog(null, ganador + " usando los villanos ha ganado ya que " + perdedor + 
                        " se ha retirado del juego" + " . Apretar OK para volver al menu principal"); 
                TableroStratego.contadorVictoriasVillanos++;
              }
              else {
                  JOptionPane.showMessageDialog(null, ganador + " usando los heroes ha ganado ya que " + perdedor + 
                        " se ha retirado del juego" + " . Apretar OK para volver al menu principal"); 
                  TableroStratego.contadorVictoriasHeroes++;
              }
              String FECHA=String.valueOf(datos.getfECHA());
              String EstadoVictoria="Derrota";
              datos.agregarFecha(FECHA, datos.UsuarioLogeado, datos.SegundoUsuario, EstadoVictoria);
            }
            else {
                 ganador = datos.UsuarioLogeado;

                if (TableroStratego.esHeroe) {
                JOptionPane.showMessageDialog(null, ganador + " usando los heroes ha ganado ya que " + perdedor + 
                        " se ha retirado del juego" + " . Apretar OK para volver al menu principal"); 
                TableroStratego.contadorVictoriasHeroes++;
              }
              else {
                  JOptionPane.showMessageDialog(null, ganador + " usando los villanos ha ganado ya que " + perdedor + 
                        " se ha retirado del juego" + " . Apretar OK para volver al menu principal"); 
                  TableroStratego.contadorVictoriasVillanos++;
              }
                 String FECHA=String.valueOf(datos.getfECHA());
                 String EstadoVictoria="Victoria";
              datos.agregarFecha(FECHA, datos.UsuarioLogeado, datos.SegundoUsuario, EstadoVictoria);
            }

        Usuarios usuarioGanador = datos.buscarUsuario(ganador);
        if (usuarioGanador != null) {
            usuarioGanador.IncrementarPuntos(3);
        }       
            menu = new Menu(login, datos);
            menu.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnRendirseActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Eliminados;
    private javax.swing.JPanel Tablero;
    private javax.swing.JButton btnRendirse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTurnos;
    private javax.swing.JTextArea txtAreaEliminados;
    // End of variables declaration//GEN-END:variables
}
