/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ar466
 */
public class Menu extends javax.swing.JFrame {
    DatosUsuario datos;
    Login login;

    MiPerfil perfil;
    UniversoMarvel marvel;

    
   
    /**
     * Creates new form Menu
     */
    public Menu(Login login,DatosUsuario datos) {
        initComponents();
        this.setSize(818, 538);
        setLocationRelativeTo(this);
        this.login=login; 
        this.datos=datos;
     
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPartidadNueva = new javax.swing.JButton();
        btnMiPerfil = new javax.swing.JButton();
        btnUniversoMarvel = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel1 = new FondoPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnPartidadNueva.setBackground(new java.awt.Color(19, 24, 21));
        btnPartidadNueva.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnPartidadNueva.setForeground(new java.awt.Color(255, 255, 255));
        btnPartidadNueva.setText("STRATEGO");
        btnPartidadNueva.setAutoscrolls(true);
        btnPartidadNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidadNuevaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPartidadNueva);
        btnPartidadNueva.setBounds(370, 130, 120, 30);

        btnMiPerfil.setBackground(new java.awt.Color(190, 53, 46));
        btnMiPerfil.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnMiPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnMiPerfil.setText("MI PERFIL");
        btnMiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(btnMiPerfil);
        btnMiPerfil.setBounds(380, 210, 110, 30);

        btnUniversoMarvel.setBackground(new java.awt.Color(59, 144, 178));
        btnUniversoMarvel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        btnUniversoMarvel.setForeground(new java.awt.Color(255, 255, 255));
        btnUniversoMarvel.setText("UNIVERSO MARVEL");
        btnUniversoMarvel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUniversoMarvelActionPerformed(evt);
            }
        });
        getContentPane().add(btnUniversoMarvel);
        btnUniversoMarvel.setBounds(360, 290, 140, 30);

        btnCerrarSesion.setBackground(new java.awt.Color(45, 148, 59));
        btnCerrarSesion.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("CERRAR SESION");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion);
        btnCerrarSesion.setBounds(360, 370, 140, 30);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres cerrar sesión?", "Confirmación de cierre de sesión", JOptionPane.OK_CANCEL_OPTION);
    if (respuesta == JOptionPane.OK_OPTION) {
        login.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnMiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiPerfilActionPerformed
        // TODO add your handling code here:
        perfil=new MiPerfil(login,datos);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMiPerfilActionPerformed

    private void btnPartidadNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidadNuevaActionPerformed
        // TODO add your handling code here:
      SegundoPlayer pedirsegundo = new SegundoPlayer(login,datos);
        pedirsegundo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPartidadNuevaActionPerformed

    private void btnUniversoMarvelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUniversoMarvelActionPerformed
        // TODO add your handling code here:
        marvel=new UniversoMarvel(login,datos);
        marvel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUniversoMarvelActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMiPerfil;
    private javax.swing.JButton btnPartidadNueva;
    private javax.swing.JButton btnUniversoMarvel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel
    {
        private Image imagen;
        @Override
        public void paint(Graphics g){
        {
            imagen = new ImageIcon(getClass().getResource("/imagenes/PRINCIPAL.png")).getImage(); 
            g.drawImage(imagen,0, 0, getWidth(), getHeight(),this);
            setOpaque(false);
            super.paint(g);
        }
        }
    }
}
